<a href="https://colab.research.google.com/github/imrannizal/RobotBidders-G6/blob/main/colab/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Preprocessing is an important step to modify our data into meaningful representation.

Note: Preprocessing is mainly done on **Google Colab**

In [112]:
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [113]:
# import dataset from google drive
bids_df = pd.read_csv("/content/drive/MyDrive/WID3011_DeepLearning_Project/bids.csv")
test_df = pd.read_csv("/content/drive/MyDrive/WID3011_DeepLearning_Project/test.csv")
train_df = pd.read_csv("/content/drive/MyDrive/WID3011_DeepLearning_Project/train.csv")

Preprocessing start

In [30]:
test_df

,bidder_id,payment_account,address
0,49bb5a3c944b8fc337981cc7a9ccae41u31d7,a3d2de7675556553a5f08e4c88d2c228htx90,5d9fa1b71f992e7c7a106ce4b07a0a754le7c
1,a921612b85a1494456e74c09393ccb65ylp4y,a3d2de7675556553a5f08e4c88d2c228rs17i,a3d2de7675556553a5f08e4c88d2c228klidn
2,6b601e72a4d264dab9ace9d7b229b47479v6i,925381cce086b8cc9594eee1c77edf665zjpl,a3d2de7675556553a5f08e4c88d2c228aght0
3,eaf0ed0afc9689779417274b4791726cn5udi,a3d2de7675556553a5f08e4c88d2c228nclv5,b5714de1fd69d4a0d2e39d59e53fe9e15vwat
4,cdecd8d02ed8c6037e38042c7745f688mx5sf,a3d2de7675556553a5f08e4c88d2c228dtdkd,c3b363a3c3b838d58c85acf0fc9964cb4pnfa
...,...,...,...
4695,bef56983ba78b2ee064443ae95972877jfkyd,0f235a6dfea5a5885d63968826b748b4q4dra,a98a4841db165de919d29cb49d0bc306cq21h
4696,4da45cc915c32d4368ac7e773d92d4affwqrr,9e0adf7481c422654d4d0a849e0e50abiumen,e23d9777cddc347de82d839b2e54b22ecopkp
4697,0d0e6220bf59ab9a0c5b5987fb2c34a9p33f9,7df4ebd184668b4257f740b11d4519afq7kr1,b650404e1ab5d177020221277c3e9306qegyl
4698,4981c32c54dde65b79dbc48fd9ab6457caqze,a3d2de7675556553a5f08e4c88d2c2284qlm0,9c35320088eaf32046a51a96ebb2e658i479u
4699,7ade70030d559a6c255be2f6feca17acnrqs0,a3d2de7675556553a5f08e4c88d2c228vo1hu,a3d2de7675556553a5f08e4c88d2c228la8g8

In [55]:
train_df['outcome'].value_counts()

outcome
0.0    1910
1.0     103
Name: count, dtype: int64

In [57]:
bids_df[bids_df['bidder_id'].isin(train_df['bidder_id'])]['bidder_id'].value_counts()

bidder_id
f5b2bbad20d1d7ded3ed960393bec0f40u6hn    515033
197e90906939267ace2422e78e8e83889znqp    236413
a58ace8b671a7531c88814bc86b2a34cf0crb    192565
9655ccc7c0c193f1549475f02c54dce45kjw7    161935
6c8ffec692e88d81e1b18d47818abb04v6llr     84319
                                          ...
ce22684df495e376e32ac95d3ceb1164t37l2         1
792edafa0603516a57932e6103e9dd54ajar7         1
424b638423f4862b2a84f22ec25fa22eb2c8p         1
5de403f3d49221bfa7116570a4d572d8m19sh         1
fff2c070d8200e0a09150bd81452ce29ngcnv         1
Name: count, Length: 1984, dtype: int64

In [77]:
bids_df[bids_df['bidder_id'].isin(train_df['bidder_id'])]

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url
1,1,668d393e858e8126275433046bbd35c6tywop,aeqok,furniture,phone1,9759243157894736,in,50.201.125.84,jmqlhflrzwuay9c
5,5,e8291466de91b0eb4e1515143c7f74dexy2yr,3vi4t,mobile,phone7,9759243157894736,ru,91.107.221.27,vasstdc27m7nks3
9,9,a58ace8b671a7531c88814bc86b2a34cf0crb,3zpkj,sporting goods,phone4,9759243210526315,za,123.28.123.226,vasstdc27m7nks3
10,10,a58ace8b671a7531c88814bc86b2a34cf0crb,z6j8b,sporting goods,phone10,9759243210526315,ng,209.80.85.101,adgjz71s3p2oiau
13,13,7e34a26c4c339e875997f4b9239d2b5fscng4,nbx39,mobile,phone13,9759243263157894,in,143.183.225.33,e5i17pk9wygxewv
...,...,...,...,...,...,...,...,...,...
7656321,7656321,f5b2bbad20d1d7ded3ed960393bec0f40u6hn,gja6c,sporting goods,phone1,9709222000000000,za,231.197.103.67,pqzlexr3qrl6gmx
7656323,7656323,9655ccc7c0c193f1549475f02c54dce45kjw7,1f9t0,sporting goods,phone718,9709222000000000,us,199.76.204.89,vasstdc27m7nks3
7656325,7656325,93e3c34171ab65e0b031dc67461e48b478u36,jmny0,jewelry,phone892,9709222052631578,id,136.144.47.247,36phop3q8vduhf5
7656326,7656326,03aafab9868455b78f0723eda86698ba9v9rm,lw44y,mobile,phone16,9709222052631578,in,5.146.235.202,oqknoadbcbcm6so
7656331,7656331,f5b2bbad20d1d7ded3ed960393bec0f40u6hn,gja6c,sporting goods,phone80,9709222052631578,za,80.237.28.246,5xgysg14grlersa

In [75]:
bids_df[bids_df['auction'] == 'jqx39']['merchandise'].value_counts()

merchandise
jewelry             196425
mobile              129476
sporting goods      100240
home goods           94734
office equipment      6531
furniture             4532
clothing              2221
books and music       1890
computers             1298
Name: count, dtype: int64

In [114]:
train_df[train_df['outcome'] == 1.0]

,bidder_id,payment_account,address,outcome
21,5354c02817e47f28e60e44a40ca5e48dll4sz,1862ef3b7965993cc975a1161010e810w2bwo,58e5dc4d38d886f6c7abf0c264a51cb7alhj2,1.0
50,9434778d2268f1fa2a8ede48c0cd05c097zey,ee3295c7b31a1e9116ebf0cf2df68ed1ac8ts,627fe7481f01372c02333477471cb237qt2vf,1.0
51,aabc211b4cf4d29e4ac7e7e361371622pockb,a3d2de7675556553a5f08e4c88d2c228pxtr6,a3d2de7675556553a5f08e4c88d2c228bxn98,1.0
58,68d468e15e0de0bab9694cdca8e799eb2j8kn,a3d2de7675556553a5f08e4c88d2c228vf08k,767150cd5a97ed796bfc58456f5500250dsv7,1.0
77,1cbd9081de4481ada66f1853737f7684ddjd1,a3d2de7675556553a5f08e4c88d2c228buft1,a3d2de7675556553a5f08e4c88d2c228pijoz,1.0
...,...,...,...,...
1936,458c8c4e10e5c1b29e3fbe5ee56d46e8y3fb3,97ee873207ff7c57e70c50637c93c11eqsyjy,480aca092e44d3e23a015e51d8e7daa4hhcss,1.0
1942,022ac3a7ce986049d9a4bede83ccf9ddctvg6,57aec2c76d2db80cf61c2543d15ef9f82tplj,c57c64adcc43ce50d99f184d87981d87yz2di,1.0
1968,6c11cc7744fb52a632306ca8bf966cd1e4zxx,0875307e1731af94b3b64725ad0deb7dg45aa,a10741281aa478c1f3ce0c965debb359rzk56,1.0
1970,17a321c4a0d925ca80507effa52330ac5n5r7,9366947fbdda1fc29952043326a70b07z0n0q,a3d2de7675556553a5f08e4c88d2c228zf3p2,1.0
2001,aaa686462ebb950550fc1c6136ffb273vkrc5,a3d2de7675556553a5f08e4c88d2c2286ehkq,07b8bf2a239664db3e50cc0e5cade252ewn6d,1.0

In [116]:
bids_df[bids_df['bidder_id'] == "40e00fd204d0ce97110032bfc47f423d0bgrd"]

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url
764489,764489,40e00fd204d0ce97110032bfc47f423d0bgrd,qp6cy,office equipment,phone728,9763761473684210,fr,244.3.78.79,jg0gq3xvauy89e0
772506,772506,40e00fd204d0ce97110032bfc47f423d0bgrd,ndb8t,office equipment,phone728,9763803421052631,fr,244.3.78.79,jg0gq3xvauy89e0
793272,793272,40e00fd204d0ce97110032bfc47f423d0bgrd,ndb8t,office equipment,phone728,9763862894736842,fr,244.3.78.79,jg0gq3xvauy89e0
796699,796699,40e00fd204d0ce97110032bfc47f423d0bgrd,ndb8t,office equipment,phone728,9763872631578947,fr,244.3.78.79,yk7e77gsb0p6ujs
800638,800638,40e00fd204d0ce97110032bfc47f423d0bgrd,ndb8t,office equipment,phone728,9763883315789473,fr,244.3.78.79,e5emfgprmopbwcj
...,...,...,...,...,...,...,...,...,...
2006895,2006895,40e00fd204d0ce97110032bfc47f423d0bgrd,xelvl,office equipment,phone46,9770753526315789,au,8.116.0.253,2b3krdoih6penn4
2007282,2007282,40e00fd204d0ce97110032bfc47f423d0bgrd,xelvl,office equipment,phone46,9770756315789473,au,8.116.0.253,18f5tqa1nzlvgki
2007725,2007725,40e00fd204d0ce97110032bfc47f423d0bgrd,xelvl,office equipment,phone46,9770759368421052,au,8.116.0.253,d2welszz3u6382w
2008101,2008101,40e00fd204d0ce97110032bfc47f423d0bgrd,xelvl,office equipment,phone46,9770762210526315,au,8.116.0.253,ll81jv4xrnlf4up
2008621,2008621,40e00fd204d0ce97110032bfc47f423d0bgrd,xelvl,office equipment,phone46,9770766000000000,au,8.116.0.253,rmpni3642z7q4mo

In [118]:
bids_df['url'].value_counts()

url
vasstdc27m7nks3    3499409
7zyltxp0hh36vpp      22297
z3qzkki3dy6ndjb      17909
q0skvht51258k93      12350
vwjvx8n5d6yjwlj      10446
                    ...
uoynybqc86adpng          1
0fc36cy473eq9gk          1
wbcrokbztxbyqll          1
l7pbnawy1zyo4c4          1
12bfhd5ormj9zaw          1
Name: count, Length: 1786351, dtype: int64