<a href="https://colab.research.google.com/github/imrannizal/RobotBidders-G6/blob/main/colab/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Preprocessing is an important step to modify our data into meaningful representation.

Assumption:
- This is taken from an online platform
- Auction: the account of

Note: Preprocessing is mainly done on **Google Colab**

In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import pandas as pd

Mounted at /content/drive

In [81]:
# import dataset from google drive
bids_df = pd.read_csv("/content/drive/MyDrive/WID3011_DeepLearning_Project/bids.csv")
test_df = pd.read_csv("/content/drive/MyDrive/WID3011_DeepLearning_Project/test.csv")
train_df = pd.read_csv("/content/drive/MyDrive/WID3011_DeepLearning_Project/train.csv")

# Feature one
Preprocessing start

In [ ]:
test_df

,bidder_id,payment_account,address
0,49bb5a3c944b8fc337981cc7a9ccae41u31d7,a3d2de7675556553a5f08e4c88d2c228htx90,5d9fa1b71f992e7c7a106ce4b07a0a754le7c
1,a921612b85a1494456e74c09393ccb65ylp4y,a3d2de7675556553a5f08e4c88d2c228rs17i,a3d2de7675556553a5f08e4c88d2c228klidn
2,6b601e72a4d264dab9ace9d7b229b47479v6i,925381cce086b8cc9594eee1c77edf665zjpl,a3d2de7675556553a5f08e4c88d2c228aght0
3,eaf0ed0afc9689779417274b4791726cn5udi,a3d2de7675556553a5f08e4c88d2c228nclv5,b5714de1fd69d4a0d2e39d59e53fe9e15vwat
4,cdecd8d02ed8c6037e38042c7745f688mx5sf,a3d2de7675556553a5f08e4c88d2c228dtdkd,c3b363a3c3b838d58c85acf0fc9964cb4pnfa
...,...,...,...
4695,bef56983ba78b2ee064443ae95972877jfkyd,0f235a6dfea5a5885d63968826b748b4q4dra,a98a4841db165de919d29cb49d0bc306cq21h
4696,4da45cc915c32d4368ac7e773d92d4affwqrr,9e0adf7481c422654d4d0a849e0e50abiumen,e23d9777cddc347de82d839b2e54b22ecopkp
4697,0d0e6220bf59ab9a0c5b5987fb2c34a9p33f9,7df4ebd184668b4257f740b11d4519afq7kr1,b650404e1ab5d177020221277c3e9306qegyl
4698,4981c32c54dde65b79dbc48fd9ab6457caqze,a3d2de7675556553a5f08e4c88d2c2284qlm0,9c35320088eaf32046a51a96ebb2e658i479u
4699,7ade70030d559a6c255be2f6feca17acnrqs0,a3d2de7675556553a5f08e4c88d2c228vo1hu,a3d2de7675556553a5f08e4c88d2c228la8g8

In [ ]:
train_df['outcome'].value_counts()

outcome
0.0    1910
1.0     103
Name: count, dtype: int64

In [ ]:
bids_df[bids_df['bidder_id'].isin(train_df['bidder_id'])]['bidder_id'].value_counts()

bidder_id
f5b2bbad20d1d7ded3ed960393bec0f40u6hn    515033
197e90906939267ace2422e78e8e83889znqp    236413
a58ace8b671a7531c88814bc86b2a34cf0crb    192565
9655ccc7c0c193f1549475f02c54dce45kjw7    161935
6c8ffec692e88d81e1b18d47818abb04v6llr     84319
                                          ...
ce22684df495e376e32ac95d3ceb1164t37l2         1
792edafa0603516a57932e6103e9dd54ajar7         1
424b638423f4862b2a84f22ec25fa22eb2c8p         1
5de403f3d49221bfa7116570a4d572d8m19sh         1
fff2c070d8200e0a09150bd81452ce29ngcnv         1
Name: count, Length: 1984, dtype: int64

In [ ]:
bids_df[bids_df['bidder_id'].isin(train_df['bidder_id'])]

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url
1,1,668d393e858e8126275433046bbd35c6tywop,aeqok,furniture,phone1,9759243157894736,in,50.201.125.84,jmqlhflrzwuay9c
5,5,e8291466de91b0eb4e1515143c7f74dexy2yr,3vi4t,mobile,phone7,9759243157894736,ru,91.107.221.27,vasstdc27m7nks3
9,9,a58ace8b671a7531c88814bc86b2a34cf0crb,3zpkj,sporting goods,phone4,9759243210526315,za,123.28.123.226,vasstdc27m7nks3
10,10,a58ace8b671a7531c88814bc86b2a34cf0crb,z6j8b,sporting goods,phone10,9759243210526315,ng,209.80.85.101,adgjz71s3p2oiau
13,13,7e34a26c4c339e875997f4b9239d2b5fscng4,nbx39,mobile,phone13,9759243263157894,in,143.183.225.33,e5i17pk9wygxewv
...,...,...,...,...,...,...,...,...,...
7656321,7656321,f5b2bbad20d1d7ded3ed960393bec0f40u6hn,gja6c,sporting goods,phone1,9709222000000000,za,231.197.103.67,pqzlexr3qrl6gmx
7656323,7656323,9655ccc7c0c193f1549475f02c54dce45kjw7,1f9t0,sporting goods,phone718,9709222000000000,us,199.76.204.89,vasstdc27m7nks3
7656325,7656325,93e3c34171ab65e0b031dc67461e48b478u36,jmny0,jewelry,phone892,9709222052631578,id,136.144.47.247,36phop3q8vduhf5
7656326,7656326,03aafab9868455b78f0723eda86698ba9v9rm,lw44y,mobile,phone16,9709222052631578,in,5.146.235.202,oqknoadbcbcm6so
7656331,7656331,f5b2bbad20d1d7ded3ed960393bec0f40u6hn,gja6c,sporting goods,phone80,9709222052631578,za,80.237.28.246,5xgysg14grlersa

In [ ]:
bids_df[bids_df['auction'] == 'jqx39']['merchandise'].value_counts()

merchandise
jewelry             196425
mobile              129476
sporting goods      100240
home goods           94734
office equipment      6531
furniture             4532
clothing              2221
books and music       1890
computers             1298
Name: count, dtype: int64

In [30]:
train_df[train_df['outcome'] == 1.0]

,bidder_id,payment_account,address,outcome
21,5354c02817e47f28e60e44a40ca5e48dll4sz,1862ef3b7965993cc975a1161010e810w2bwo,58e5dc4d38d886f6c7abf0c264a51cb7alhj2,1.0
50,9434778d2268f1fa2a8ede48c0cd05c097zey,ee3295c7b31a1e9116ebf0cf2df68ed1ac8ts,627fe7481f01372c02333477471cb237qt2vf,1.0
51,aabc211b4cf4d29e4ac7e7e361371622pockb,a3d2de7675556553a5f08e4c88d2c228pxtr6,a3d2de7675556553a5f08e4c88d2c228bxn98,1.0
58,68d468e15e0de0bab9694cdca8e799eb2j8kn,a3d2de7675556553a5f08e4c88d2c228vf08k,767150cd5a97ed796bfc58456f5500250dsv7,1.0
77,1cbd9081de4481ada66f1853737f7684ddjd1,a3d2de7675556553a5f08e4c88d2c228buft1,a3d2de7675556553a5f08e4c88d2c228pijoz,1.0
...,...,...,...,...
1936,458c8c4e10e5c1b29e3fbe5ee56d46e8y3fb3,97ee873207ff7c57e70c50637c93c11eqsyjy,480aca092e44d3e23a015e51d8e7daa4hhcss,1.0
1942,022ac3a7ce986049d9a4bede83ccf9ddctvg6,57aec2c76d2db80cf61c2543d15ef9f82tplj,c57c64adcc43ce50d99f184d87981d87yz2di,1.0
1968,6c11cc7744fb52a632306ca8bf966cd1e4zxx,0875307e1731af94b3b64725ad0deb7dg45aa,a10741281aa478c1f3ce0c965debb359rzk56,1.0
1970,17a321c4a0d925ca80507effa52330ac5n5r7,9366947fbdda1fc29952043326a70b07z0n0q,a3d2de7675556553a5f08e4c88d2c228zf3p2,1.0
2001,aaa686462ebb950550fc1c6136ffb273vkrc5,a3d2de7675556553a5f08e4c88d2c2286ehkq,07b8bf2a239664db3e50cc0e5cade252ewn6d,1.0

In [ ]:
bids_df[bids_df['bidder_id'] == "40e00fd204d0ce97110032bfc47f423d0bgrd"]

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url
764489,764489,40e00fd204d0ce97110032bfc47f423d0bgrd,qp6cy,office equipment,phone728,9763761473684210,fr,244.3.78.79,jg0gq3xvauy89e0
772506,772506,40e00fd204d0ce97110032bfc47f423d0bgrd,ndb8t,office equipment,phone728,9763803421052631,fr,244.3.78.79,jg0gq3xvauy89e0
793272,793272,40e00fd204d0ce97110032bfc47f423d0bgrd,ndb8t,office equipment,phone728,9763862894736842,fr,244.3.78.79,jg0gq3xvauy89e0
796699,796699,40e00fd204d0ce97110032bfc47f423d0bgrd,ndb8t,office equipment,phone728,9763872631578947,fr,244.3.78.79,yk7e77gsb0p6ujs
800638,800638,40e00fd204d0ce97110032bfc47f423d0bgrd,ndb8t,office equipment,phone728,9763883315789473,fr,244.3.78.79,e5emfgprmopbwcj
...,...,...,...,...,...,...,...,...,...
2006895,2006895,40e00fd204d0ce97110032bfc47f423d0bgrd,xelvl,office equipment,phone46,9770753526315789,au,8.116.0.253,2b3krdoih6penn4
2007282,2007282,40e00fd204d0ce97110032bfc47f423d0bgrd,xelvl,office equipment,phone46,9770756315789473,au,8.116.0.253,18f5tqa1nzlvgki
2007725,2007725,40e00fd204d0ce97110032bfc47f423d0bgrd,xelvl,office equipment,phone46,9770759368421052,au,8.116.0.253,d2welszz3u6382w
2008101,2008101,40e00fd204d0ce97110032bfc47f423d0bgrd,xelvl,office equipment,phone46,9770762210526315,au,8.116.0.253,ll81jv4xrnlf4up
2008621,2008621,40e00fd204d0ce97110032bfc47f423d0bgrd,xelvl,office equipment,phone46,9770766000000000,au,8.116.0.253,rmpni3642z7q4mo

In [5]:
test_df = bids_df[bids_df['bidder_id'] == "9434778d2268f1fa2a8ede48c0cd05c097zey"]
test_df
#test_df is just the datatable of the bidder "9434778d2268f1fa2a8ede48c0cd05c097zey"

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url
2351666,2351666,9434778d2268f1fa2a8ede48c0cd05c097zey,7qncv,jewelry,phone82,9631918789473684,tr,195.70.249.18,1a3esl7g1a4iszy
2353120,2353120,9434778d2268f1fa2a8ede48c0cd05c097zey,uotsf,jewelry,phone82,9631924894736842,tr,195.70.249.18,2xg72q72h44m9h4
2354680,2354680,9434778d2268f1fa2a8ede48c0cd05c097zey,jqx39,jewelry,phone57,9631931736842105,lk,33.21.12.36,l5djirkby14dcve
2354749,2354749,9434778d2268f1fa2a8ede48c0cd05c097zey,jqx39,jewelry,phone35,9631932000000000,in,26.5.70.166,9fxz5etwphe0s9w
2355004,2355004,9434778d2268f1fa2a8ede48c0cd05c097zey,jqx39,jewelry,phone649,9631933105263157,lk,136.147.112.144,4spdk2478800is6
...,...,...,...,...,...,...,...,...,...
7645615,7645615,9434778d2268f1fa2a8ede48c0cd05c097zey,jqx39,jewelry,phone59,9709173736842105,in,209.29.47.82,3pbqfppa38stulm
7646447,7646447,9434778d2268f1fa2a8ede48c0cd05c097zey,jqx39,jewelry,phone41,9709177578947368,bd,185.11.117.222,mx4zm951jp5zdp4
7649334,7649334,9434778d2268f1fa2a8ede48c0cd05c097zey,jqx39,jewelry,phone263,9709191000000000,in,80.53.77.69,3rsvgzgrlb55erh
7651390,7651390,9434778d2268f1fa2a8ede48c0cd05c097zey,jqx39,jewelry,phone41,9709200526315789,bd,185.11.117.222,l6myr4qpm8sfa6z
7656251,7656251,9434778d2268f1fa2a8ede48c0cd05c097zey,jqx39,jewelry,phone23,9709221736842105,in,123.174.101.3,vasstdc27m7nks3

In [31]:
def get_time_median(bidder_id):

  iterations = bids_df[bids_df['bidder_id'] == bidder_id]['time']
  i = len(iterations) - 1

  for idx in range(i):
    print(iterations.iloc[idx + 1] - iterations.iloc[idx])

get_time_median("aabc211b4cf4d29e4ac7e7e361371622pockb")

#test2 = test_df.head(2)
#difference = test2["time"].iloc[1] - test2["time"].iloc[0]
#print(difference)

36315789474
3052631579
6105263158
7473684210
1578947368
31263157895
7578947369
5421052631
1263157895
2736842105
894736842
9421052632
24315789474
6315789473
26000000000
18526315790
2736842105
30578947368
8894736843
10000000000
7578947368
5052631579
6421052631
4631578948
25157894737
9000000000
15947368421
14894736842
10000000000
2157894737
10894736842
1052631579
9315789473
14789473685
24421052631
315789474
16894736842
947368421
6736842105
1789473685
5105263157
684210527
5421052631
17315789474
1000000000
17368421053
11631578947
59210526316
38894736842
19842105263
27210526316
9315789474
68263157894
14421052632
8736842105
74421052632
1894736842
6631578947
12000000000
2526315790
17947368421
31105263158
8315789473
40631578948
24000000000
6894736842
1842105263
2315789474
34631578947
2526315789
36421052632
315789474
13789473684
83631578947
40947368421
11157894737
40157894737
5894736842
28631578947
100105263158
5421052632
93263157895
225000000000
118631578947
83421052632
95736842105
250157894737
177526315789
36315789474
14000000000
38789473684
17052631579
105263158
4000000000
6789473684
53842105263
319052631579
188789473684
185842105264
49684210526
84526315789
7578947369
157894737
13000000000
47157894737
3210526315
17263157895
50421052632
29210526315
1684210527
3894736842
7210526316
116894736842
119736842105
86157894737
13684210526
105263158
40631578947
19000000000
52631579
184947368421
179578947369
45315789474
5684210526
9894736842
5105263158
1789473684
2578947368
947368422
2947368421
15947368421
13842105263
58000000000
157894737
178842105263
69421052631
14263157895
9368421053
3736842105
105263158
4631578947
8684210527
2526315789
4157894737
33263157895
13684210526
1631578947
13473684211
11210526316
11473684210
10052631579
66578947369
24105263157
4421052632
42105263158
3789473684
8473684211
15578947368
15052631579
9789473684
24210526316
39000000000
16210526316
38210526316
1578947368
13315789474
7473684210
31052631579
10000000000
7894736842
130736842106
12789473684
3526315789
73842105263
1894736842
31578947369
19789473684
7263157895
1947368421
3210526316
1684210526
37368421053
5315789473
35684210527
19578947368
6789473684
11894736842
10473684211
14473684210
3210526316
4210526316
6947368421
13789473684
12263157895
2736842105
17684210527
33263157894
10052631579
62947368421
45315789474
11315789474
26526315789
42894736842
6947368421
0
12105263158
40157894737
2947368421
7631578947
53842105264
24052631579
2684210526
29263157895
48684210526
56210526316
8368421052
526315790
2368421052
52631579
684210527
105263158
10473684210
21000000000
47894736842
1105263158
2210526316
47263157895
328421052631
156157894737
196210526316
6000000000
314473684210
25789473685
124105263158
7526315789
70631578947
2473684211
30631578947
88105263158
24578947369
30736842105
9421052631
7210526316
62421052632
2315789473
10526315790
28157894737
33421052631
18421052632
157894737
112947368421
5684210526
10263157895
684210526
23157894737
28842105263
70105263158
28947368421
37947368421
36578947369
130210526315
37000000000
77947368421
49315789474
9052631579
19421052632
12157894737
61736842105
97210526316
7368421052
5789473684
58052631579
39684210527
53894736842
5894736842
33842105263
9526315790
39526315789
5894736842
7631578947
1157894737
18368421053
7473684210
5157894737
12894736842
9842105264
1631578947
2421052632
19473684210
210526316
17263157895
5368421052
12842105263
157894737
1526315790
684210526
16263157895
25421052631
17631578948
36473684210
13894736842
8736842106
18473684210
29578947369
11263157894
11052631579
35210526316
26631578947
23368421053
5052631579
52000000000
6263157895
36315789473
11421052632
10842105263
4421052632
25578947368
9842105263
17789473684
4210526316
66736842106
3736842105
27473684210
15052631579
46473684211
5105263158
20052631579
26210526315
4947368421
13000000000
2263157895
20052631579
3526315790
28210526315
5000000000
13789473685
2368421052
46526315790
2052631579
18526315789
13842105263
9421052632
20684210526
43947368421
894736842
17578947369
4105263158
45263157894
22684210527
53789473684
44210526316
45473684210
73789473684
26263157895
29631578948
2000000000
17684210526
20842105263
35421052632
9105263158
66421052631
23473684211
63368421052
34789473684
21631578948
42526315789
81631578948
11631578947
6315789474
10421052631
1000000000
16157894737
578947369
17947368421
71421052631
27842105263
141631578948
16526315789
85105263158
201684210526
96789473685
22000000000
184000000000
186631578947
14842105263
171000000000
45684210526
87421052632
3947368421
137315789474
17263157895
18368421052
87631578948
95000000000
842105263
7842105263
1947368421
118210526316
101315789473
70789473685
14473684210
26631578947
60736842106
1894736842
69736842105
8157894737
147631578947
31789473685
71736842105
106000000000
50105210526316
5263157894
947368421
1736842106
3894736842
105263158
4000000000
7105263158
9105263157
13631578948
1210526316
3105263157
3368421053
4105263158
1789473684
5105263158
4947368421
3368421053
4842105263
10894736842
2789473684
3578947369
578947368
4263157895
105263158
16105263158
789473684
2684210526
3157894737
789473684
789473684
23105263158
2157894737
1263157895
5526315789
2631578948
15263157894
13736842106
27157894737
1526315789
6947368421
3789473684
16105263158
263157895
2052631579
3526315789
1578947369
15578947368
3526315790
4473684210
15526315790
7157894737
24473684210
10684210526
1736842106
14894736842
1684210526
1684210526
789473685
2105263157
473684211
6947368421
2526315790
1157894736
1947368421
263157895
6894736842
6000000000
7421052632
16000000000
1263157895
11631578947
1368421053
3000000000
13789473684
3631578947
6263157895
5157894737
3105263158
1947368421
4684210526
105263158
2473684210
736842106
4315789473
5842105264
2315789473
1789473684
2631578948
1473684210
3526315790
2842105263
2631578947
52631579
3631578948
2000000000
7315789473
2157894737
3736842105
4368421053
2631578947
4368421053
1947368421
2526315790
4842105263
1210526316
2684210526
105263158
684210526
578947368
4000000000
263157895
2947368421
2000000000
12947368421
157894737
684210526
789473685
5473684210
1315789474
578947368
210526316
2052631579
4315789474
2526315789
1684210527
5105263157
1578947369
8842105263
1315789474
4052631579
1157894736
1052631579
2578947369
789473684
578947368
2052631579
1421052632
4947368421
1421052632
3842105263
578947368
3105263158
5789473684
3789473685
368421052
7421052632
1000000000
368421052
3526315790
9105263158
3052631579
2421052631
2052631579
3105263158
9368421053
684210526
2421052632
52631579
3263157894
52631579
6210526316
5315789474
526315789
2421052632
157894737
2947368421
13210526315
2473684211
5263157895
1526315789
3421052632
6315789473
210526316
1631578948
421052631
52631579
1947368421
1263157895
3631578947
526315790
1684210526
2894736842
2421052632
842105263
52631579
1000000000
2473684210
11105263158
3052631579
2894736842
157894737
5578947369
1578947368
3578947368
2421052632
4000000000
2631578947
11157894737
6684210527
684210526
5684210526
11578947369
3631578947
5473684211
3736842105
10368421052
52631579
3210526316
12315789474
315789474
105263157
25368421053
684210526
1157894737
4315789474
5210526316
736842105
526315789
947368421
3736842106
7842105263
18578947368
1631578948
3315789473
5263157895
2473684211
210526315
7631578948
1947368421
6842105263
5947368421
2421052632
3315789473
1210526316
7631578947
3368421053
1157894737
11684210526
7263157895
1210526316
2315789473
15947368422
11894736842
894736842
1631578947
4052631579
16157894737
3368421053
9157894736
7052631579
0
11947368421
4684210527
3947368421
4368421052
4473684211
12684210526
10736842105
5789473685
526315789
6842105263
2526315790
20894736842
4578947368
4315789474
4368421053
210526315
6315789474
315789474
421052631
4736842106
7842105263
105263158
4000000000
947368421
6789473684
7684210526
5210526316
7947368421
1000000000
3210526316
1473684210
4052631579
684210527
15368421052
8526315790
9894736842
9526315789
3842105264
5578947368
7894736842
52631579
2842105263
3421052632
736842105
3157894737
7631578947
2473684211
7052631579
2000000000
6473684210
473684211
6210526316
6052631578
2000000000
4368421053
3315789474
105263158
10105263158
9684210526
368421053
10631578947
18421052631
8315789474
3631578948
3421052631
5263157895
23210526316
2210526315
9315789474
1421052632
22315789473
5947368421
14368421053
1578947368
105263158
3842105264
18000000000
736842105
4210526316
15263157894
9052631579
16473684211
19842105263
789473684
7526315790
2368421052
473684211
9684210526
14473684211
24894736842
33578947368
12052631579
6368421053
368421052
7789473685
473684210
19526315790
263157894
14894736842
52631579
3789473685
28736842105
23473684210
5526315790
5368421052
105263158
421052632
52631579
15315789474
105263157
3789473685
27210526315
9736842106
2894736842
2315789474
13368421052
13210526316
105263158
9421052631
23157894737
53736842106
3578947368
12842105263
6210526316
26052631579
170894736842
4578947368
23000000000
631578948
112105263158
33105263158
6000000000
30684210526
6157894737
19578947368
18000000000
3526315790
1263157894
2000000000
17000000000
473684211
315789474
10736842105
1526315789
2315789474
21210526316
2842105263
3526315789
105263158
5736842106
19052631578
16263157895
4315789474
9473684210
22684210527
1684210526
46736842105
8052631579
9631578948
9052631579
3842105263
4263157894
20631578948
2157894737
1684210526
3157894737
368421052
5000000000
5157894737
2947368421
105263158
631578948
1789473684
2052631579
631578947
5315789474
1631578947
11105263158
1157894737
2000000000
6000000000
12421052632
15052631578
3210526316
10894736842
13631578948
11473684210
1157894737
1000000000
11105263158
10421052632
10000000000
14684210526
7421052631
9578947369
24157894737
9526315789
157894737
1578947368
4368421053
368421053
11105263158
4263157894
6421052632
7052631579
368421053
8789473684
52631579
46368421052
2736842106
5315789473
22473684211
1736842105
52631579
263157895
13526315789
19736842105
11315789474
9684210526
3578947369
789473684
5789473684
157894737
526315790
1210526315
3052631579
3210526316
5157894737
6473684211
14842105263
4157894737
26263157894
7421052632
28789473684
11000000000
210526316
10210526316
20947368421
1684210526
8263157895
1631578947
2736842105
157894737
16789473684
5421052632
14105263158
1421052631
105263158
578947369
8421052631
7157894737
1000000000
8684210527
2000000000
1263157894
3315789474
7105263158
4052631579
421052631
4473684211
2736842105
2947368421
7000000000
3473684211
4894736842
9210526316
11105263158
7263157894
1315789474
14421052632
3894736842
11578947368
10526315790
3684210526
3421052631
6631578948
7894736842
157894737
3368421052
13894736842
684210527
3263157895
9368421052
526315790
1210526315
2368421053
26210526316
6736842105
4736842105
20263157895
1631578947
3842105264
16157894736
8263157895
210526316
3578947368
9157894737
1526315790
1684210526
3157894737
11421052631
2473684211
52631579
2263157895
13473684210
52631579
52631579
3947368421
12263157895
6473684210
157894737
11473684211
105263158
2578947368
26842105263
3526315790
3473684210
12578947369
11947368421
105263158
4684210526
13578947368
9473684211
1894736842
11789473684
1210526316
684210526
5947368421
4000000000
14789473685
5526315789
473684211
1842105263
10315789473
8894736843
947368421
1631578947
8157894737
29315789473
9894736843
4842105263
2842105263
27789473684
157894737
19578947368
23421052632
6842105263
7842105263
3473684211
24789473684
5105263158
2789473684
26421052632
736842105
12736842105
2789473684
8315789474
1421052632
684210526
2105263158
10210526316
1000000000
4105263158
52631579
578947368
12157894737
842105263
2052631579
526315789
2578947369
105263158
3473684210
12105263158
10842105263
5736842106
4842105263
14947368421
368421052
2631578948
14000000000
11736842105
14157894737
1105263158
15631578947
2421052632
10052631579
4789473684
6421052631
3473684211
10736842105
2315789474
18263157895
10736842105
157894737
3263157894
4052631579
12684210527
15105263158
842105263
6157894737
3052631579
1684210526
2631578947
4947368421
684210527
6947368421
9578947368
4578947369
6578947368
6526315789
105263158
41157894737
5631578948
14210526315
5368421053
3368421053
52631579
21684210526
1157894737
6210526315
39684210527
16526315789
8000000000
789473684
7578947369
5368421053
7736842105
5894736842
6052631579
1000000000
13263157895
1052631579
1157894736
29842105264
3210526315
7736842106
3052631579
11052631578
4000000000
18947368422
2052631578
157894737
5578947369
28789473684
5526315789
10368421053
263157895
1684210526
5842105263
6000000000
15157894737
631578947
3894736843
2263157894
52631579
12578947369
157894737
2000000000
947368421
15947368421
473684210
2368421053
7210526316
2578947368
105263158
1368421053
17789473684
2315789473
21210526316
1421052632
8526315789
684210527
1526315789
17684210526
2526315790
1842105263
578947368
5421052632
368421053
11473684210
684210526
52631579
11105263158
947368421
2947368421
2421052632
8157894737
12789473684
10105263158
9210526316
736842105
2736842105
2578947369
105263158
20684210526
26263157895
11105263158
3631578947
4473684210
3263157895
1105263158
4842105263
315789474
3052631579
684210526
4473684211
23210526315
105263158
947368421
3473684211
16789473684
1315789474
3578947368
6473684211
11105263158
4631578947
842105263
1684210527
3263157894
2526315790
1157894737
11526315789
6000000000
18210526316
3736842105
894736842
1684210527
2894736842
421052631
5210526316
3105263158
7684210526
2684210527
1684210526
894736842
157894737
578947368
1105263158
2631578947
1263157895
1210526316
1894736842
5157894737
3157894737
17315789473
894736843
3684210526
10210526316
2578947368
5631578947
4789473685
52631579
15789473684
13315789474
6894736842
4473684210
4263157895
1315789474
2578947368
3736842105
52631579
11578947369
1894736842
5157894737
3421052631
12947368421
14263157895
6315789474
4052631579
315789473
842105263
4157894737
14631578948
6684210526
1736842105
2473684211
5105263158
1894736842
12736842105
9631578947
3368421053
2894736842
5526315790
2105263157
7315789474
2473684211
1789473684
1263157895
17000000000
263157894
157894737
1947368421
10578947369
2736842105
5894736842
4368421053
1526315789
2105263158
2368421053
368421052
4684210527
8578947368
10578947368
1631578948
105263158
2263157894
52631579
7473684211
10526315789
6263157895
2315789474
19578947368
9368421053
0
14368421053
3368421052
7105263158
6894736842
1842105263
7263157895
9263157895
12105263158
12526315789
2578947369
17157894736
3578947369
7210526316
9894736842
8842105263
4842105263
9157894737
5105263158
11736842105
5947368421
5105263158
3894736842
5684210526
21000000000
2315789474
2473684211
15421052631
1789473684
12263157895
3052631579
6105263158
736842105
789473684
11894736843
16789473684
16421052631
842105264
1052631578
1000000000
11315789474
6842105263
4263157895
2157894737
2421052631
2000000000
105263158
10421052632
10684210526
5631578948
1473684210
19368421053
9631578947
18052631579
3368421053
6736842105
7052631579
16894736842
10631578947
4052631579
2473684211
7052631579
3842105263
15631578947
11789473685
23631578947
12473684210
7052631579
12789473685
12000000000
18789473684
105263158
8421052631
2263157895
7263157895
13578947368
315789474
105263158
59578947368
7210526316
105263158
7684210526
4263157895
4368421053
2052631579
5368421052
8578947369
17789473684
10842105263
4263157895
17842105263
6157894737
11631578947
1000000000
16894736842
8789473684
12736842106
473684210
15789473684
368421053
29894736842
24894736842
4000000000
9578947369
2421052631
24052631579
4526315790
9052631579
1315789473
4052631579
2210526316
8473684211
2157894736
473684211
8736842105
2578947369
3000000000
1631578947
2894736842
2578947368
7526315790
12421052632
2157894736
13473684211
16894736842
2210526316
736842105
3157894737
29000000000
13473684210
12368421053
526315790
9052631578
2578947369
12789473684
8578947369
36473684210
8842105263
1210526316
19368421053
1263157894
17947368421
105263158
18684210527
105263158
4578947368
13736842105
57157894737
11736842105
10631578948
27210526315
3473684211
12105263158
11526315789
14368421053
8421052632
27157894736
19421052632
4315789474
17736842105
10421052632
14105263157
10736842106
1736842105
4947368421
1894736842
3315789474
52631579
8105263158
17368421052
12736842106
44631578947
3631578947
38105263158
18684210526
842105264
9052631579
3263157894
105263158
1000000000
1105263158
10578947369
4157894736
2105263158
1000000000
3631578948
7684210526
5000000000
1684210526
2421052632
7473684210
18421052632
315789474
4421052631
8894736842
10421052632
4000000000
2947368421
5263157895
6947368421
29736842105
75578947368
5105263158
9315789474
3157894737
1105263158
25842105263
17894736842
31263157895
3578947368
7210526316
6684210526
1894736842
31578947369
4368421052
11368421053
7000000000
8736842105
7526315790
24157894737
4894736842
32631578947
6947368421
7052631579
2421052632
8842105263
16894736842
421052632
2157894736
9736842106
5000000000
4000000000
7684210526
13684210526
43421052632
1789473684
20315789474
19052631579
1052631579
2789473684
3105263158
1736842105
18736842105
6368421053
842105263
2421052632
9052631579
15368421052
4000000000
2473684211
1631578947
3473684211
8157894736
1210526316
2842105263
13789473685
13421052631
24263157895
473684210
30894736843
9894736842
11842105263
2315789474
13526315789
12631578947
2210526316
28578947369
5210526315
9052631579
2684210527
1526315789
1578947369
5789473684
14368421052
33789473685
40157894736
1105263158
1368421053
17315789474
105263158
25263157894
15947368421
12578947369
947368421
5578947368
1894736842
1263157895
1684210526
2842105264
2263157894
6894736842
1473684211
3421052631
6157894737
25789473685
10105263157
8421052632
83894736842
315789474
7736842105
27000000000
5210526316
1947368421
1736842105
736842105
421052632
3473684211
1263157894
6947368421
27421052632
6736842105
1210526316
3473684210
28473684211
9263157895
2842105263
5842105263
3000000000
6421052632
3263157894
263157895
52631579
23789473684
37052631579
1105263158
14315789474
9421052631
8157894737
26210526316
4947368421
1052631579
8263157895
421052631
5894736842
421052632
10315789474
6315789473
15947368421
16684210527
1421052631
3105263158
4473684211
2631578947
4263157895
5631578947
24894736842
2210526316
2105263158
3210526316
631578947
6263157895
2315789474
52631579
11473684210
10315789474
7105263158
3052631579
9421052631
3526315790
2894736842
12157894737
3157894736
8315789474
15789473684
7894736842
19263157895
8105263158
4894736842
4105263158
15947368421
2947368421
30052631579
4473684211
2000000000
2526315789
1368421053
4368421052
7157894737
2894736842
5421052632
5157894737
5421052631
9947368421
15578947369
3263157895
52631578
6473684211
1578947368
3789473685
10473684210
3578947369
7473684210
33894736842
10736842105
2736842106
1263157894
4736842106
1578947368
2368421053
17789473684
5000000000
17000000000
6631578947
9526315790
4736842105
7368421053
1789473684
6052631579
7789473684
21000000000
13000000000
4105263158
11736842105
842105263
1789473685
3684210526
894736842
4789473684
5052631579
1210526316
1052631579
263157895
263157894
7210526316
7105263158
3473684211
6578947368
2421052632
1526315789
8526315790
2631578947
2052631579
3947368421
6000000000
473684210
3210526316
2000000000
1578947369
3842105263
1315789474
3842105263
2105263158
8684210526
4684210526
1736842105
6052631579
631578948
12736842105
157894737
3157894737
4736842105
894736842
263157895
5684210526
1000000000
1210526316
12947368421
5315789474
28052631579
2000000000
8157894736
4105263158
11315789474
7526315790
8789473684
9736842105
34000000000
11368421053
6368421052
8473684211
526315789
11631578948
8894736842
5210526316
2000000000
6526315789
6368421053
1052631579
1315789473
421052632
2052631579
578947368
37263157895
1210526316
29052631579
6473684210
3736842105
7263157895
526315790
18000000000
736842105
421052632
1052631578
4894736843
5631578947
3000000000
4736842105
14842105263
17631578948
5526315789
1263157895
6789473684
3736842105
1157894737
10052631579
5315789474
7526315789
7210526316
10052631579
4526315790
9105263157
736842106
10368421052

# Feature 2: Ranking bidders
This part is to see the rank of all bidders in a certain auction 'jqx39'. we see that bots usually bids in the later phase of the auction item.

In [88]:
temp = bids_df[bids_df['bidder_id'].isin(train_df['bidder_id'])]
temp[temp['auction'] == 'jqx39']

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url
2351200,2351200,6e178db6d17d21aa88aaca5bf15c2761lc500,jqx39,jewelry,phone99,9631916842105263,sa,174.12.78.255,omwhmwzvrn6ycq6
2351203,2351203,3a5420301c0dacbc5675f6f09aac0143tuodl,jqx39,jewelry,phone25,9631916894736842,vn,48.186.219.240,a9oo5hbdagf0r9c
2351211,2351211,9655ccc7c0c193f1549475f02c54dce45kjw7,jqx39,sporting goods,phone290,9631916894736842,de,13.173.247.96,vasstdc27m7nks3
2351212,2351212,7264bde42ef4fe3fa19cc7c6d64696cf7pqtd,jqx39,jewelry,phone648,9631916947368421,in,244.27.103.108,bm707sbje2nxucf
2351224,2351224,4af5e2532224f9f7d1d039704573d9205jbkv,jqx39,sporting goods,phone52,9631916947368421,sa,202.163.102.223,n01ruj9s6henwwn
...,...,...,...,...,...,...,...,...,...
7656251,7656251,9434778d2268f1fa2a8ede48c0cd05c097zey,jqx39,jewelry,phone23,9709221736842105,in,123.174.101.3,vasstdc27m7nks3
7656261,7656261,9655ccc7c0c193f1549475f02c54dce45kjw7,jqx39,sporting goods,phone398,9709221736842105,kr,50.222.161.36,vasstdc27m7nks3
7656296,7656296,7264bde42ef4fe3fa19cc7c6d64696cf7pqtd,jqx39,jewelry,phone75,9709221894736842,in,48.2.195.154,d59i8c6v0onpbdc
7656308,7656308,7264bde42ef4fe3fa19cc7c6d64696cf7pqtd,jqx39,jewelry,phone3,9709221947368421,in,181.56.172.244,a0f2j3fwdr0711h
7656313,7656313,9655ccc7c0c193f1549475f02c54dce45kjw7,jqx39,sporting goods,phone115,9709222000000000,iq,10.162.170.57,vasstdc27m7nks3

In [89]:
temp = temp.merge(train_df[['bidder_id', 'outcome']], on='bidder_id', how='right')
temp = temp[temp['auction'] == 'jqx39']
temp

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url,outcome
253,2354263.0,fa64831ab5ade55daee13f852c16b0a84ujt0,jqx39,mobile,phone65,9.631930e+15,cn,216.22.211.228,vasstdc27m7nks3,0.0
254,2354566.0,fa64831ab5ade55daee13f852c16b0a84ujt0,jqx39,mobile,phone4,9.631931e+15,in,198.114.223.255,vasstdc27m7nks3,0.0
257,2400865.0,fa64831ab5ade55daee13f852c16b0a84ujt0,jqx39,mobile,phone57,9.632024e+15,in,80.53.77.69,s9vakg6dt092zq5,0.0
258,2426502.0,fa64831ab5ade55daee13f852c16b0a84ujt0,jqx39,mobile,phone65,9.632087e+15,cn,23.62.150.210,rm77nw8nyin6vou,0.0
261,2440434.0,fa64831ab5ade55daee13f852c16b0a84ujt0,jqx39,mobile,phone65,9.632123e+15,cn,43.169.3.38,tttm5ntc679zx6v,0.0
...,...,...,...,...,...,...,...,...,...,...
3070622,4680601.0,aaa686462ebb950550fc1c6136ffb273vkrc5,jqx39,sporting goods,phone55,9.642753e+15,us,33.244.88.8,yxlccopjmr1t4sz,1.0
3070625,4684488.0,aaa686462ebb950550fc1c6136ffb273vkrc5,jqx39,sporting goods,phone232,9.642789e+15,us,160.252.46.57,yxlccopjmr1t4sz,1.0
3070637,4707372.0,aaa686462ebb950550fc1c6136ffb273vkrc5,jqx39,sporting goods,phone383,9.642981e+15,us,44.128.26.85,yxlccopjmr1t4sz,1.0
3070653,7242949.0,aaa686462ebb950550fc1c6136ffb273vkrc5,jqx39,sporting goods,phone65,9.706949e+15,cn,115.6.15.187,vasstdc27m7nks3,1.0
3071250,3400601.0,0381a69b7a061e9ace2798fd48f1f537mgq57,jqx39,office equipment,phone11,9.636754e+15,sa,54.212.21.87,cgb17jpn1ixq9hw,0.0

In [104]:
temp2 = temp[['bid_id', 'bidder_id', 'time', 'outcome']]
temp2.sort_values('time', inplace=True)
temp2.reset_index(drop=True, inplace=True)
time_diffs = temp2['time'].diff().dropna()

temp2[['bidder_id', 'outcome']].value_counts()

/tmp/ipykernel_30104/3807537001.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp2.sort_values('time', inplace=True)

bidder_id                              outcome
9655ccc7c0c193f1549475f02c54dce45kjw7  1.0        62485
7264bde42ef4fe3fa19cc7c6d64696cf7pqtd  0.0        21908
047558bebab9292a5d4c85d6ee768784j2hdd  0.0        20849
6e178db6d17d21aa88aaca5bf15c2761lc500  0.0        15513
3a5420301c0dacbc5675f6f09aac0143tuodl  0.0         9425
                                                  ...
0381a69b7a061e9ace2798fd48f1f537mgq57  0.0            1
f8c42ccd10c3fe515e53082f0cde9a18oxgws  0.0            1
f8d0d52114da74d98800dc7553008705dth38  0.0            1
024937af9ea18a2b57e4f08762d181f7s8a3z  0.0            1
fa6bfb4a2156dc8e73a713cdab85bc4bmcmwr  0.0            1
Name: count, Length: 349, dtype: int64

In [106]:
bids_df[bids_df['url'] == 'yxlccopjmr1t4sz']

,bid_id,bidder_id,auction,merchandise,device,time,country,ip,url
2470244,2470244,aaa686462ebb950550fc1c6136ffb273vkrc5,6jn6a,sporting goods,phone383,9632202578947368,nl,127.50.189.4,yxlccopjmr1t4sz
2472322,2472322,aaa686462ebb950550fc1c6136ffb273vkrc5,gja6c,sporting goods,phone1814,9632208526315789,de,218.110.11.166,yxlccopjmr1t4sz
2472977,2472977,aaa686462ebb950550fc1c6136ffb273vkrc5,racqh,sporting goods,phone5479,9632210473684210,us,246.7.173.155,yxlccopjmr1t4sz
2473433,2473433,aaa686462ebb950550fc1c6136ffb273vkrc5,dt2k0,sporting goods,phone5480,9632211842105263,de,142.54.31.152,yxlccopjmr1t4sz
2497998,2497998,aaa686462ebb950550fc1c6136ffb273vkrc5,1f9t0,sporting goods,phone21,9632287105263157,us,247.175.62.105,yxlccopjmr1t4sz
...,...,...,...,...,...,...,...,...,...
5796660,5796660,f0ea23ccdbdc11a73806ccc38492a98e2p25s,cew0k,books and music,phone55,9698858789473684,us,243.141.236.49,yxlccopjmr1t4sz
5798704,5798704,f0ea23ccdbdc11a73806ccc38492a98e2p25s,rcb25,books and music,phone52,9698871631578947,us,73.158.50.103,yxlccopjmr1t4sz
5799203,5799203,f0ea23ccdbdc11a73806ccc38492a98e2p25s,xsj5g,books and music,phone46,9698874736842105,us,195.91.147.13,yxlccopjmr1t4sz
5800273,5800273,f0ea23ccdbdc11a73806ccc38492a98e2p25s,cew0k,books and music,phone996,9698881842105263,us,173.240.61.89,yxlccopjmr1t4sz
5800868,5800868,f0ea23ccdbdc11a73806ccc38492a98e2p25s,62d9x,books and music,phone143,9698885473684210,ca,120.44.168.181,yxlccopjmr1t4sz

# Feature 3: Number of devices per bidder

In [246]:
num_devices_df = bids_df[bids_df['bidder_id'].isin(train_df['bidder_id'])]
num_devices_df = num_devices_df[['bidder_id', 'device']]
num_devices_df = num_devices_df[num_devices_df['bidder_id'] == 'f5b2bbad20d1d7ded3ed960393bec0f40u6hn']
num_devices_df['device'].nunique()

2618

In [125]:
num_devices_df

Empty DataFrame
Columns: [bidder_id, device]
Index: []

# Feature 4: Number of unique IP address a bidding account has

In [245]:
num_IP_df = bids_df[bids_df['bidder_id'].isin(train_df['bidder_id'])]
num_IP_df = num_IP_df[['bidder_id', 'ip']]
num_IP_df = num_IP_df[num_IP_df['bidder_id'] == 'f5b2bbad20d1d7ded3ed960393bec0f40u6hn']
num_IP_df['ip'].nunique()

101275

# Feature 5: Number of unique countries a bidding account has

In [244]:
num_country_df = bids_df[bids_df['bidder_id'].isin(train_df['bidder_id'])]
num_country_df = num_country_df[['bidder_id', 'country']]
num_country_df = num_country_df[num_country_df['bidder_id'] == 'f5b2bbad20d1d7ded3ed960393bec0f40u6hn']
num_country_df['country'].nunique()

98

# Feature 6: Number of bids a bidding account has done

In [259]:
total_bids_df = bids_df[bids_df['bidder_id'].isin(train_df['bidder_id'])]
total_bids_df = total_bids_df.merge(train_df[['bidder_id', 'outcome']], on='bidder_id', how='right')
total_bids_df = total_bids_df[['bidder_id', 'outcome']]
#total_bids_df = total_bids_df[total_bids_df['bidder_id'] == 'f5b2bbad20d1d7ded3ed960393bec0f40u6hn']
total_bids_df.value_counts()

bidder_id                              outcome
f5b2bbad20d1d7ded3ed960393bec0f40u6hn  0.0        515033
197e90906939267ace2422e78e8e83889znqp  0.0        236413
a58ace8b671a7531c88814bc86b2a34cf0crb  0.0        192565
9655ccc7c0c193f1549475f02c54dce45kjw7  1.0        161935
6c8ffec692e88d81e1b18d47818abb04v6llr  0.0         84319
                                                   ...
53856dce9187b16f2cf5e4e58f5d0397h7tz6  0.0             1
53691811bd992911edb9f5f64f49d8f5luk1f  0.0             1
52c441804b89bc20e4c8dd625bf163f27o2zb  0.0             1
b853c1e4d6a4657d35705772ca6cfdc3qtox5  0.0             1
b77312a06d10e22e3caca85fc7fe0342b2adf  0.0             1
Name: count, Length: 2013, dtype: int64

In [273]:
total_bids_df = bids_df[bids_df['bidder_id'].isin(train_df['bidder_id'])]
total_bids_df = total_bids_df.merge(train_df[['bidder_id', 'outcome']], on='bidder_id', how='right')
total_bids_df = total_bids_df[['bidder_id', 'device', 'outcome']]
#total_bids_df = total_bids_df[total_bids_df['bidder_id'] == 'f5b2bbad20d1d7ded3ed960393bec0f40u6hn']
temp = total_bids_df.groupby('bidder_id')['device'].nunique().reset_index()
temp = temp.merge(train_df[['bidder_id', 'outcome']], on='bidder_id', how='right')
temp = temp.sort_values('device', ascending=False)
temp

                                  bidder_id  device  outcome
1823  f5b2bbad20d1d7ded3ed960393bec0f40u6hn    2618      0.0
1870  a58ace8b671a7531c88814bc86b2a34cf0crb    2020      0.0
1719  6c8ffec692e88d81e1b18d47818abb04v6llr    1610      0.0
648   6713e820273f591bdff7d26a48ee30c5k4iii    1575      0.0
418   ae45f9b94d86f931c84c94f3975e3d7bkv2r0    1494      0.0
...                                     ...     ...      ...
364   74f153bd134afc92866a6bc5cceb2088120y0       0      0.0
750   d1780c224460a0c20d5c2f5f68714c5264xd0       0      0.0
1511  a4475cf8808f8951dd5163ded3ee8032g9vxd       0      0.0
1551  db12e9cad5e847cd7a40ec1ee649e475iwzqo       0      0.0
741   59fe751fb6c277016b7ebe3609aa1b15vhg7w       0      0.0

[2013 rows x 3 columns]

In [250]:
train_df[train_df['outcome'] == 0.0]

,bidder_id,payment_account,address,outcome
0,91a3c57b13234af24875c56fb7e2b2f4rb56a,a3d2de7675556553a5f08e4c88d2c228754av,a3d2de7675556553a5f08e4c88d2c228vt0u4,0.0
1,624f258b49e77713fc34034560f93fb3hu3jo,a3d2de7675556553a5f08e4c88d2c228v1sga,ae87054e5a97a8f840a3991d12611fdcrfbq3,0.0
2,1c5f4fc669099bfbfac515cd26997bd12ruaj,a3d2de7675556553a5f08e4c88d2c2280cybl,92520288b50f03907041887884ba49c0cl0pd,0.0
3,4bee9aba2abda51bf43d639013d6efe12iycd,51d80e233f7b6a7dfdee484a3c120f3b2ita8,4cb9717c8ad7e88a9a284989dd79b98dbevyi,0.0
4,4ab12bc61c82ddd9c2d65e60555808acqgos1,a3d2de7675556553a5f08e4c88d2c22857ddh,2a96c3ce94b3be921e0296097b88b56a7x1ji,0.0
...,...,...,...,...
2008,369515b3af4f8ca582f90271d30b14b6r52aw,a1f85275793c4a782f0a668711f41b927ivc9,e6882cf204a9482edd042b6e31791dfctxzx8,0.0
2009,f939c17ffc7c39ac9b35b69e5e75179fv9pe2,a3d2de7675556553a5f08e4c88d2c2286s1m2,b9b03d5a127eb07aeb9163cdcf524e1344ac9,0.0
2010,c806dbb2decba0ed3c4ff5e2e60a74c2wjvbl,a3d2de7675556553a5f08e4c88d2c22856leq,d02c2b288b8aabd79ff47118aff41a2dqwzwc,0.0
2011,0381a69b7a061e9ace2798fd48f1f537mgq57,fd87037ce0304077079c749f420f0b4c54uo0,f030a221726fbcdfc4dc7dfd1b381a112hieq,0.0
2012,84a769adc98498f52debfe57b93a0789556f4,fbe0ce34d6546ebd9e4c63afc68b085byd2tf,a3d2de7675556553a5f08e4c88d2c228fib6p,0.0

# temp

In [285]:
temp = bids_df[bids_df['bidder_id'].isin(train_df['bidder_id'])]
temp = temp[temp['bidder_id'] == 'd6517684989560cbb0da1fb2f5bbba9b9y2st']
temp['auction'].nunique()

1621

In [286]:
bids_df['auction'].value_counts()

auction
jqx39    537347
jefix    208926
no958     74020
opnq4     71446
du967     69633
          ...
24tog         1
3bwk0         1
eolh2         1
1bfcd         1
ldaze         1
Name: count, Length: 15051, dtype: int64